labonnerecette/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from recette import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout,{'next_page': '/'}, name='logout'),
    url(r'^register/$', views.register, name='register'),

    url(r'^', include('recette.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recette/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^recipe/(?P<id>\d+)/', views.recipe, name="recipe"),
    url(r'^add_recipe', views.add, name="add"),
    url(r'^delete_recipe/(?P<id>\d+)/', views.delete, name='delete'),
    url(r'^modify_recipe/(?P<id>\d+)/', views.modify, name='modify'),
    url(r'^profil/$', views.profil, name='profil'),
    url(r'^search_result/$', views.search, name='search'),
    url(r'^mailAtFriends/(?P<id>\d+)/$', views.mailAtFriends, name='mailAtFriends'),
]

recette/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

DIFFICULT = (
    ('F', 'Facile'),
    ('M', 'Moyen'),
    ('D', 'Difficile'),
)

NOTE = [(i,i) for i in range(6)]

PRICE = (
    ('1', 'Peu couteux'),
    ('2', 'Couteux'),
    ('3', 'Très couteux'),
)

class Recipe(models.Model):
    user = models.ForeignKey(User, default=1, editable=False)
    title = models.CharField(max_length=100, verbose_name='Titre')
    type = models.ForeignKey('Type', null=True)
    difficult = models.CharField(max_length=1, choices=DIFFICULT, default='F', verbose_name='Difficulté')
    price = models.CharField(max_length=1, choices=PRICE, default='1', verbose_name='Echelle de prix')
    preparationTime = models.IntegerField(null=True, default=20, verbose_name='Temps de préparation')
    cookingTime = models.IntegerField(null=True, default=20, verbose_name='Temps de cuisson')
    breakTime = models.IntegerField(null=True, verbose_name='Temps de repos')
    informationPreparation = models.TextField()


class Type(models.Model):
    title = models.CharField(max_length=256)
    detail = models.TextField()

    def __str__(self):
        return self.title

class Ingredient(models.Model):
    recipe = models.ForeignKey('Recipe', null=True,editable=False)
    name = models.CharField(max_length=100)
    qty = models.CharField(max_length=100)

class Pics(models.Model):
    recipe = models.ForeignKey('Recipe', null=True, editable=False)
    image = models.ImageField(upload_to="picsRecipe", max_length=100)

class Comments(models.Model):
    recipe = models.ForeignKey('Recipe', blank=True, null=True)
    user = models.ForeignKey(User, blank=True, null=True, default=1)
    message = models.TextField()
    created_at = models.DateTimeField(default=datetime.now, blank=True, null=True)

class Note(models.Model):
    recipe = models.ForeignKey('Recipe', blank=True, null=True)
    user = models.ForeignKey(User, blank=True, null=True)
    note = models.IntegerField(choices=NOTE)

recette/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms.models import inlineformset_factory
from recette.models import Recipe, Pics, Note, Comments, Ingredient

class RegistrationForm(UserCreationForm):
     class Meta:
         model = User
         fields = ['last_name','first_name','username', 'email']

PicFormset = inlineformset_factory(Recipe, Pics, fields=('image', ), can_delete=False, extra=3)
IngredientFormset = inlineformset_factory(Recipe, Ingredient, fields=('name','qty'), can_delete=False, extra=8)


class RecipeForm(forms.ModelForm):
    informationPreparation = forms.CharField(required=True, widget=forms.Textarea(attrs={'cols': 40, 'rows': 2}), label='Informations sur la préparation')
    class Meta:
        model = Recipe
        exclude = []


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['note']


class CommentForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea(attrs={'cols': 100, 'rows': 5}))
    class Meta:
        model = Comments
        fields = ['message']


class FriendForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'L\'adresse email de mon ami(e)'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Mon message'}))

recette/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Avg
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from recette.forms import RegistrationForm, RecipeForm, PicFormset, FriendForm, IngredientFormset, CommentForm, NoteForm
from recette.models import Recipe, Pics, Type, Ingredient, Comments, Note
from django.core.mail import EmailMultiAlternatives

def index(request):
    # on recupere les dernieres recettes ajouter
    recipes = Recipe.objects.all().order_by('-id');
    typeRecipe = None
    if request.method == 'GET':
        if request.GET.get('type'):
            type = request.GET['type']
            typeRecipe = Type.objects.get(id=type)
            recipes = Recipe.objects.filter(type=type)
    paginator = Paginator(recipes, 10)
    page = request.GET.get('page')
    try:
        recipes = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        recipes = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        recipes = paginator.page(paginator.num_pages)
    contexte = {
        'typeRecipe': typeRecipe,
        'recipes': recipes,
    }
    return render(request, 'recette/index.html', contexte)


def register(request):
    if request.method == 'POST':
        user_form = RegistrationForm(request.POST)
        if user_form.is_valid():
            user = User.objects.create_user(request.POST['username'], request.POST['email'],
                                            request.POST['password1'])
            user.first_name = request.POST['first_name']
            user.last_name = request.POST['last_name']
            user.save()
            context = {
                'form': AuthenticationForm,
                'success_message': 'success'
            }
        return render(request, 'registration/login.html', context)
    else:
        user_form = RegistrationForm()
        context = {
            'form': user_form,
        }
    return render(request, 'registration/register.html', context)


def recipe(request, id):
    if request.method == 'POST':
        form_note = NoteForm(request.POST)
        form_comment = CommentForm(request.POST)

        if form_note.is_valid():
            note = form_note.save()
            note.recipe = Recipe.objects.get(id=id)
            note.user = request.user
            note.save()

        if form_comment.is_valid():
            comment = form_comment.save()
            comment.recipe = Recipe.objects.get(id=id)
            comment.user = request.user
            comment.save()

    recipe = Recipe.objects.get(id=id)
    ingredients = Ingredient.objects.filter(recipe=id)
    pics = Pics.objects.filter(recipe=id)

    comments = Comments.objects.filter(recipe=id)
    form_comment = CommentForm()
    countComments = Comments.objects.filter(recipe=id).count()

    paginator = Paginator(comments, 3)
    page = request.GET.get('page')
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        comments = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        comments = paginator.page(paginator.num_pages)

    if (request.user.is_authenticated()):
        noted = Note.objects.filter(recipe=id, user=request.user).count()
        if noted == 0:
            form_note = NoteForm()
        else:
            form_note = ''
    else:
        form_note = ''

    countNotes = Note.objects.filter(recipe=id).count()
    averageNote = Note.objects.filter(recipe=id).aggregate(Avg('note'))

    if pics:
        context = {
           'recipe': recipe,
           'pics': pics,
           'ingredients': ingredients,
           'comments': comments,
           'form_comment': form_comment,
           'form_note': form_note,
           'averageNote': averageNote,
           'countComments': countComments,
           'countNotes' : countNotes
        }
    else:
        context = {
            'recipe': recipe,
            'urlPic': 'recette/img/no-img.jpg',
            'ingredients': ingredients,
            'comments': comments,
            'form_comment': form_comment,
            'form_note': form_note,
            'averageNote': averageNote,
            'countComments': countComments,
            'countNotes': countNotes
        }
    return render(request, 'recette/recipe.html', context)



def add(request):
    if request.method == 'POST':
        recipeForm = RecipeForm(request.POST)
        if recipeForm.is_valid():
            recipe = recipeForm.save()
            recipe.user = request.user
            recipe.save()
            ingredientForm = IngredientFormset(request.POST, instance=recipe)
            if ingredientForm.is_valid():
                ingredientForm.save()
                imgForm = PicFormset(request.POST, request.FILES, instance=recipe)
                if imgForm.is_valid():
                    imgForm.save()
                    return render(request, "recette/add.html", {
                        'recipeForm': recipeForm,
                        'ingredientForm': ingredientForm,
                        'imgForm': imgForm,
                        'success_message': 'success'
                    })

    return render(request, "recette/add.html", {
            "recipeForm": RecipeForm(),
            'ingredientForm': IngredientFormset(),
            "imgForm": PicFormset()
        })


def modify(request, id):
    recipe = get_object_or_404(Recipe, id=id)

    recipeForm = RecipeForm(instance=recipe)
    ingredientForm = IngredientFormset(instance=recipe)
    imgForm = PicFormset(instance=recipe)

    if request.method == 'POST':
        recipeForm = RecipeForm(request.POST)
        if recipeForm.is_valid():
            recipe.title = recipeForm.cleaned_data['title']
            recipe.type = recipeForm.cleaned_data['type']
            recipe.price = recipeForm.cleaned_data['price']
            recipe.difficult = recipeForm.cleaned_data['difficult']
            recipe.preparationTime = recipeForm.cleaned_data['preparationTime']
            recipe.cookingTime = recipeForm.cleaned_data['cookingTime']
            recipe.breakTime = recipeForm.cleaned_data['breakTime']
            recipe.informationPreparation = recipeForm.cleaned_data['informationPreparation']
            recipe.user = request.user
            recipe.save()

            # serializer = serializers.serialize('json', ingredients)
            # return HttpResponse(serializer)


            recipes = Recipe.objects.filter(user_id=request.user.id)
            context = {
                'recipes': recipes,
                'success_message': 'success'
            }
            return render(request, 'recette/profil.html', context)

    return render(request, "recette/modify-recipe.html", {
        'recipe': recipe,
        'ingredientForm': ingredientForm,
        'imgForm': imgForm,
        'recipeForm': recipeForm,
    })


def delete(request, id):
    Recipe.objects.get(id=id).delete()
    recipes = Recipe.objects.filter(user_id=request.user.id)
    context = {
        'recipes': recipes
    }
    return render(request, 'recette/profil.html', context)



def profil(request):
    recipes = None;
    if request.user.is_authenticated():
        recipes = Recipe.objects.filter(user_id=request.user.id)
        context = {
            'recipes': recipes
        }
        return render(request, 'recette/profil.html', context)



# redirection ver profil
def mailAtFriends(request, id):
    if request.user.is_authenticated():
        recipe = Recipe.objects.get(id=id)

        if request.method == 'POST':
            friend_form = FriendForm(request.POST)
            if friend_form.is_valid():
                subject = request.user.first_name + ' vous a envoyé une recette'
                from_email = 'jocelynkelle@gmail.com'
                to = request.POST['email']
                text_content = 'Bonjour,' + request.user.first_name + '(' + request.user.email + ') vous a envoyé une recette.' + request.POST['message'] + '</p><a href="http://127.0.0.1:8000/recipe/' + id +'">Voir la recette de mon amis</a></p>'
                html_content = '<div>Bonjour,<br>' + request.user.first_name + '(' + request.user.email + ') vous a envoyé une recette.<br><br></div><p>' + request.POST["message"] + '</p><a href="http://127.0.0.1:8000/recipe/' + id +'">Voir la recette de mon ami</a></p>'

                msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
                msg.attach_alternative(html_content, "text/html")
                msg.send()

                recipes = None;
                recipes = Recipe.objects.filter(user_id=request.user.id)
                context = {
                    'success_send_mail': 'success',
                    'recipes': recipes
                }

                return render(request, 'recette/profil.html', context)
        else:
            friend_form = FriendForm()
            context = {
                'friend_form': friend_form,
                'recipe': recipe,
            }
            return render(request, 'recette/form_friend.html', context)
    else:
        return redirect('login')





def search(request):
    query = request.GET.get('search_query')
    criteria = ''
    orderby = ''
    if request.GET.get('criteria') and request.GET.get('orderby'):
        criteria = request.GET.get('criteria')
        orderby = request.GET.get('orderby')
        if orderby == 'desc':
            results = Recipe.objects.filter(title__contains=query).order_by('-' + criteria).select_related()
        elif orderby == 'asc':

recette/templates/recette/_base.html
{% load static %}
{% load recipe_extras %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'recette/css/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'recette/css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'recette/css/jquery.fancybox.css' %}" />
    <script src="{% static 'recette/js/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static 'recette/js/jquery.fancybox.js' %}"></script>
</head>
<body>

     <div id="header" class="row">
         <!-- logo -->
         <div class="logo col-md-5"><a href="{% url 'index' %}"><img style="margin-left:70px;" src="{% static 'recette/img/la_bonne_recette.png' %}" alt="labonnerecette" /></a></div>
        <!-- search -->
         <div class="search col-md-4">
            {% include "recette/form_search.html" %}
         </div>
        <!-- Manage user-->
         <div class="user_button col-md-3">
            {% if user.is_authenticated %}
                <p>
                    Bienvenue <strong>{{ user.last_name }} {{ user.first_name }}</strong><br>
                    <strong>{% show_count_recipe %}</strong> recettes sont en ligne !
                </p>
                <a class="btn btn-info" href="{% url 'profil' %}">Mon profil</a>
                <a class="btn btn-danger" href="{% url 'logout' %}">Déconnexion</a>
            {% else %}
             <a class="btn btn-info" href="{% url 'register' %}">S'enregistrer</a>
             <a class="btn btn-primary" href="{% url 'login' %}">Connexion</a>
            {% endif %}
         </div>
     </div>


     <div id="main_container">
         <div id="menu">
             <ul class="nav nav-pills">
                    {% show_menu %}
                    <li><a href="http://127.0.0.1:8000/recipe/{% random_id_recipe %}">Recette au hasard</a></li>
              </ul>
         </div>

         <div id="main">
            <div id="page">
                {% block contents %}{% endblock %}
            </div>
         </div>
     </div>


     <div id="footer">
     </div>

</body>
</html>

recette/templates/recette/add.html
{% extends 'recette/_base.html' %}
{% block title %}Ajouter une recette{% endblock %}
{% block contents %}
     <h1>Ajouter une recette !</h1>

    {% if success_message %}
            <h5 class="success_message">Votre recette a bien été créée ! <a href="{% url 'profil' %}">Consulter mes recettes</a></h5>
    {% endif %}

    <form action="{% url 'add' %}" class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ recipeForm.as_p }}
            {{ ingredientForm.as_p }}
            {{ priceForm.as_p }}
            {{ imgForm.as_p }}
            <input class="btn btn-primary" type="submit" value="Ajouter la recette !" />
    </form>
{% endblock %}

recette/templates/recette/form_friend.html
{% extends 'recette/_base.html' %}
{% block title %}Envoyer une recette{% endblock %}
{% block contents %}
     <h1>Envoyer à un amis la recette : {{ recipe.title }}</h1>

    <form id="friendForm" method="post" action="{% url 'mailAtFriends' recipe.id %}">
        {% csrf_token %}
        {{ friend_form.email }}
        {{ friend_form.message }}
        <input class="btn btn-primary" type="submit" value="Envoyer" />
    </form>


{% endblock %}

recette/templates/recette/form_search.html
<form method="get" action="{% url 'search' %}">
    <input type="text" id="search_query" name="search_query" placeholder="Soupe, pizza...">
</form>

recette/templates/recette/index.html
{% extends 'recette/_base.html' %}
{% block title %}Index{% endblock %}
{% block contents %}

   {% if typeRecipe %}
        <h1>{{ typeRecipe.label }}</h1>
        <div>{{ typeRecipe.detail }}</div>
   {% else %}
        <h1>Voici toutes nos recettes !</h1>
   {% endif %}

   {% if user.is_authenticated %}
      <a href="{% url 'add' %}">ajouter une recette</a>
   {% endif %}

  {% if recipes %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Photo</th>
                    <th>Titre</th>
                    <th>Difficulté</th>
                    <th>Temps de préparation</th>
                </tr>
            </thead>
            <tbody>
                {% for recipe in recipes %}
                    <tr>
                        <td>
                            <a href="{% url 'recipe' recipe.id %}">
                                <img  style="width:30%" src=" {% if recipe.pics_set.all %}
                                {% for pic in recipe.pics_set.all %}
                                    {% if forloop.counter == 1%}
                                        {{ pic.image.url }}
                                    {% endif %}
                                {% endfor %}
                            {% else %}
                                /static/recette/img/no-img.jpg
                            {% endif %}" alt="" />
                            </a>
                        </td>
                        <td>{{ recipe.title }}</td>
                        <td>{{ recipe.get_difficult_display }}</td>
                        <td>{{ recipe.preparationTime }} minutes</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="pagination">
            <span class="step-links">
                {% if recipes.has_previous %}
                    <a href="?type={{ typeRecipe.id }}&page={{ recipes.previous_page_number }}">Résultats précédent</a>
                {% endif %}

                <span class="current">
                    Page {{ recipes.number }} de {{ recipes.paginator.num_pages }}
                </span>

                {% if recipes.has_next %}
                    <a href="?type={{ typeRecipe.id }}&page={{ recettes.next_page_number }}">Résultats suivant</a>
                {% endif %}
            </span>
        </div>
    {% else %}
      <h2>Aucune recette</h2>
    {% endif %}



{% endblock %}

recette/templates/recette/profil.html
{% extends 'recette/_base.html' %}
{% block title %}Mon profil !{% endblock %}
{% block contents %}
     <h1>Mon profil !</h1>

    {% if success_send_mail %}
            <h5 class="success_message">Votre recette a été envoyé à votre ami(e)!</h5>
    {% endif %}

    {% if success_message %}
            <h5 class="success_message">Votre recette a été modifiée !</h5>
    {% endif %}

    <h3>Mes infos</h3>
        <ul>
            <li>{{ user.last_name }}</li>
            <li>{{ user.first_name }}</li>
            <li>{{ user.email }}</li>
            <li>{{ user.username }}</li>
        </ul>

    <h3>Mes recettes</h3>
        {% if recipes is None %}
            <p>Pas de recette</p>
        {% else %}
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Photo</th>
                        <th>Titre</th>
                        <th>Difficulté</th>
                        <th>Temps de préparation</th>
                        <th>Modifier</th>
                        <th>Supprimer</th>
                    </tr>
                </thead>
                <tbody>
                    {% for recipe in recipes %}
                        <tr>
                            <td>
                                <a href="{% url 'recipe' recipe.id %}">
                                    <img  style="width:30%" src=" {% if recipe.pics_set.all %}
                                    {% for pic in recipe.pics_set.all %}
                                        {% if forloop.counter == 1%}
                                            {{ pic.image.url }}
                                        {% endif %}
                                    {% endfor %}
                                {% else %}
                                    /static/recette/img/no-img.jpg
                                {% endif %}" alt="" />
                                </a>
                            </td>
                            <td>{{ recipe.title }}</td>
                            <td>{{ recipe.get_difficult_display }}</td>
                            <td>{{ recipe.preparationTime }} minutes</td>
                            <td><a class="btn btn-success" href="{% url 'modify' recipe.id %}">Modifier</a></td>
                            <td><a class="btn btn-danger" href="{% url 'delete' recipe.id %}">Supprimer</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
{% endblock %}

recette/templates/recette/recipe.html
{% extends 'recette/_base.html' %}
{% block title %}Recette - {{ recipe.title }} {% endblock %}
{% block contents %}
<div class="recipe-contain col-sm-12">
    <div class="main-recipe">
        <h1>{{ recipe.title }}</h1>
    </div>
    <div class="photos col-sm-6">
            {% if pics %}
                   {% for pic in pics %}
                        {% if forloop.counter == 1%}
                            <div id="mainPicture"><a class="fancybox" rel="gallery1" href="{{ pic.image.url }}"><img src="{{ pic.image.url }}" alt="" /></a></div>
                        {% else %}
                            <div class="others"><a class="fancybox" rel="gallery1" href="{{ pic.image.url }}"><img src="{{ pic.image.url }}" alt="" /></a></div>
                        {% endif %}
                   {% endfor %}
            {% else %}
                {% load static %}
                <img src="{% static urlPic %}" alt="" />
            {% endif %}

    </div>
    <div class="recette-right col-sm-3">
        <div class="detail">
            <span id="type">Type : </span><span>{{ recipe.type }}</span><br>
            <span id="price">Prix : </span><span>{{recipe.get_price_display }}</span><br>
            <span id="difficult">Difficulté : </span><span>{{ recipe.get_difficult_display }}</span><br>
        </div>
        <div class="temps">
            <span id="cookingTime">Temps de cuisson : </span><span>{{ recipe.cookingTime }} minutes</span><br>
            <span id="preparationTime">Temps de preparation : </span><span>{{ recipe.preparationTime }} minutes</span><br>
        </div>
        <div class="preparation">
            <span id="informationPreparation">Preparation : </span><span>{{ recipe.informationPreparation }}</span><br>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="ingredients">
            <span id="ing">Ingrédients : </span>
            <span id="enumerateIngredients">
                <ul style="margin-left: 20px;">
                {% for ingredient in ingredients %}
                    <li> {{ ingredient.qty }} {{ ingredient.name }}  </li>
                {% endfor %}
                </ul>
            </span>
        </div>
        <div class="autres">
            <a href="{% url 'mailAtFriends' recipe.id %}">Envoyer à un amis</a>
        </div>
    </div>
</div>

<div class="form_note">
        {% if user.is_authenticated %}
        <h3>Notes ({{ countNotes }}):</h3>
    <p><strong>{{ averageNote.note__avg|floatformat:"2" }}</strong> / 5</p>
            {% if form_note %}
                 <form action="{% url 'recipe' recipe.id %}" method="post">
                {{ form_note }}
                {% csrf_token %}
                 <input type="submit" class="btn btn-primary" value="Donnez une note">
                </form>
            {% else %}
                <span>Vous avez déjà voté !</span>
            {% endif %}
        {% else %}
            <a href="{% url 'login' %}">Vous devez être connecté pour pouvoir noter cette recette !</a>
        {% endif %}
    </div>

    <div class="container_comments">
        <h3>Commentaires ({{ countComments }}):</h3>
        <div class="comments">
            {% for comment in comments %}
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title"><strong>{{ comment.user }}</strong> le {{ comment.created_at }}</h3>
                  </div>
                  <div class="panel-body">{{ comment.message }}</div>
                </div>
            {% endfor %}
            <div class="pagination">
                <span class="step-links">
                    {% if comments.has_previous %}
                        <a href="?page={{ comments.previous_page_number }}">précédent</a>
                    {% endif %}

                    <span class="current">
                        Page {{ comments.number }} sur {{ comments.paginator.num_pages }}.
                    </span>

                    {% if comments.has_next %}
                        <a href="?page={{ comments.next_page_number }}">suivant</a>
                    {% endif %}
                </span>
            </div>
        </div>
        <div class="form_comments">
            {% if user.is_authenticated %}
                {% if form_comment %}
                    <h4>Ajouter un commentaire</h4>
                    <form action="{% url 'recipe' recipe.id %}" method="post">
                        {{ form_comment.message }}
                        {% csrf_token %}
                        <input type="submit" id="addComment" class="btn btn-primary" value="Ajouter un commentaire">
                    </form>
                {% endif %}
            {% else %}
                <a href="{% url 'login' %}">Connectez-vous pour laisser un commentaire à cette recette!</a>
            {% endif %}
        </div>
    </div>



<script type="text/javascript">
    $(document).ready(function() {
        $(".fancybox").fancybox();
    });
</script>
{% endblock %}

recette/templates/recette/result_search.html
{% extends "recette/_base.html" %}
{% block contents %}
    <h1>Résultats de la recherche pour : "{{ query }}"</h1>

     <div class="search-filter">
        <form method="GET" action="{% url 'search' %}">
            <span>Trier par : </span>
            <select name="criteria">
                <option {% if criteria == 'titre' %} selected="selected"{% endif %} value="titre">Titre</option>
                <option {% if criteria == 'note' %} selected="selected"{% endif %} value="note">Note moyenne</option>
                <option {% if criteria == 'difficulte' %} selected="selected"{% endif %}value="difficulte">Difficulté</option>
                <option {% if criteria == 'temps_preparation' %} selected="selected"{% endif %}value="temps_preparation">Temps de préparations</option>
            </select>
            <span>Trier par ordre : </span>
            <select name="orderby">
                <option {% if orderby == 'asc' %} selected="selected"{% endif %} value="asc">Croissant</option>
                <option {% if orderby == 'desc' %} selected="selected"{% endif %} value="desc">Décroissant</option>
            </select>
            <input type="hidden" name="page" value="{{ page }}" />
            <input type="hidden" value="{{ query }}" name="search_query"/>
            <input class="btn btn-success" type="submit" value="Filtrer" />
        </form>
     </div>

     <table class="table table-hover search-result">
        <thead>
            <tr>
                <th>Photo</th>
                <th>Titre</th>
                <th>Difficulté</th>
                <th>Note moyenne</th>
                <th>Temps de préparation</th>
            </tr>
        </thead>
        <tbody>
            {% for result in results %}
                <tr>
                    <td>
                        <a href="{% url 'recipe' result.id %}">
                            <img  style="width:30%" src=" {% if result.pics_set.all %}
                                    {% for pic in result.pics_set.all %}
                                        {% if forloop.counter == 1%}
                                            {{ pic.image.url }}
                                        {% endif %}
                                    {% endfor %}
                                {% else %}
                                    /static/recette/img/no-img.jpg
                                {% endif %}" alt="" />
                        </a>
                    <td><a href="{% url 'recipe' result.id %}">{{ result.title }}</a></td>
                    <td>{{ result.get_difficult_display }}</td>
                    <td></td>
                    <td>{{ result.preparationTime }} minutes</td>
                </tr>
            {% endfor %}
        </tbody>
     </table>

      <div class="pagination">
         <span class="step-links">
            {% if results.has_previous %}
                <a href="?search_query={{ query }}&criteria={{ criteria }}&orderby={{ orderby }}&page={{ results.previous_page_number }}">Résultats précédent</a>
            {% endif %}
            <span class="current">
                Page {{ results.number }} de {{ results.paginator.num_pages }}
            </span>
            {% if results.has_next %}
                <a href="?search_query={{ query }}&criteria={{ criteria }}&orderby={{ orderby }}&page={{ results.next_page_number }}">Résultats suivant</a>
            {% endif %}
         </span>
      </div>



{% endblock %}